language: python
python:
  - 3.6
install:
  - pip install unittest2
  - pip install -r requirements.txt
script:
  - python test.py
branches:
  only:
  - master
  - develop
  - feature-OOP-TDD
after_success:
- coveralls
